FROM python:3.6.1

MAINTAINER Ysicing Zheng<root@ysicing.net>

# pre_env

#ENV TZ "Asia/Shanghai"
#ENV TERM xterm
#ENV LANG en_US.UTF-8

# pip http
COPY pip.conf /root/.pip/pip.conf

RUN mkdir -p /data/ops
COPY . /data/ops
WORKDIR /data/ops

VOLUME ["/data/ops"]

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["bash"]



